-- Finding the total customers by countries
select
country,
count(customer_key) as total_customers
from gold_dim_customers
group by country order by total_customers desc;

-- finding total customers by gender
select
gender,
count(customer_key) as total_customers
from gold_dim_customers
group by gender
order by total_customers desc;

-- finding total products by category
select
category,
count(product_key) as total_product
from gold_dim_product
GROUP BY category
order by total_product desc;

-- Average cost in each category
select
category,
round(avg(cost),2) as average_cost
from gold_dim_product
group by category
order by average_cost desc;

-- total revenue generated by each category
select
p.category,
sum(f.sales_amount) total_revenue
from gold_fact_sales f
left join gold_dim_product p
on p.product_key=f.product_key
GROUP BY p.category
order by total_revenue desc;

-- total revenue generated by each customer
select
c.customer_key,
c.first_name, c.last_name,
sum(f.sales_amount) as total_revenue
from gold_fact_sales f
left JOIN gold_dim_customers c
on f.customer_key = c.customer_key
group by c.customer_key,
c.first_name, c.last_name
order by total_revenue desc;

-- total revenue generated by countries
select
c.country,
sum(f.quantity) as total_sold_items
from gold_fact_sales f
left JOIN gold_dim_customers c
on f.customer_key = c.customer_key
group by c.country
order by total_sold_items desc;

-- total revenue by genders
select
c.gender,
sum(f.sales_amount) as sales_by_gender
from gold_fact_sales f
left join gold_dim_customers c
on f.customer_key = c.customer_key
group  by c.gender
order by sales_by_gender desc;

-- total revenue by marital status
select
c.marital_status,
sum(f.sales_amount) as sales_by_marital_status
from gold_fact_sales f
left join gold_dim_customers c
on f.customer_key = c.customer_key
group  by c.marital_status
order by sales_by_marital_status desc;